### ISSUE TITLE
autogen: UnboundLocalError: local variable 'datetime' referenced before assignment

### ISSUE THREAD

**Issue by gangelop** [Psycojoker/prosopopee#112]
version 1.0.1
On running `prosopopee autogen -d $somedir` it fails with:

```
Traceback (most recent call last):
  File "/bin/prosopopee", line 33, in <module>
    sys.exit(load_entry_point('prosopopee==1.0.1', 'console_scripts', 'prosopopee')())
  File "/usr/lib/python3.8/site-packages/prosopopee/prosopopee.py", line 621, in main
    autogen(arguments['<folder>'], arguments['--force'])
  File "/usr/lib/python3.8/site-packages/prosopopee/autogen.py", line 81, in autogen
    build_template(folder, force)
  File "/usr/lib/python3.8/site-packages/prosopopee/autogen.py", line 68, in build_template
    files=sorted(files_grabbed, key=get_exif)
  File "/usr/lib/python3.8/site-packages/prosopopee/autogen.py", line 48, in get_exif
    return datetime
UnboundLocalError: local variable 'datetime' referenced before assignment
```

This is the offending function. Clearly there is one case where datetime does not get set.
```python
def get_exif(filename):
    exif_data = {}
    exif = Image.open(filename)._getexif()
    if exif is not None:
        for (tag, value) in exif.items():
            decoded = TAGS.get(tag, tag)
            exif_data[decoded] = value
        if 'DateTime' in exif_data:
            datetime = exif_data['DateTime']
    else:
        datetime = strftime("%Y:%m:%d %H:%M:00", gmtime(os.path.getmtime(filename)))
    return datetime
```
I can't look into it further right now. I might later.

**Comment by gangelop** [comment]
This would fix the bug but there's got to be a more elegant way to write it.
```python
def get_exif(filename):
    exif_data = {}
    exif = Image.open(filename)._getexif()
    if exif is not None:
        for (tag, value) in exif.items():
            decoded = TAGS.get(tag, tag)
            exif_data[decoded] = value
        if 'DateTime' in exif_data:
            datetime = exif_data['DateTime']
        else:
            datetime = strftime("%Y:%m:%d %H:%M:00", gmtime(os.path.getmtime(filename)))
    else:
        datetime = strftime("%Y:%m:%d %H:%M:00", gmtime(os.path.getmtime(filename)))
    return datetime
```

**Comment by gangelop** [comment]
of course there was a more elegant solution.
We first attempt to populate the `exif_data` and then `if` it's populated we use it `else` we use `getmtime` so it's always one or the other. No error here because `exif_data` is already initialized as `{}`.

```python
def get_exif(filename):
    exif_data = {}
    exif = Image.open(filename)._getexif()
    if exif is not None:
        for (tag, value) in exif.items():
            decoded = TAGS.get(tag, tag)
            exif_data[decoded] = value
    if 'DateTime' in exif_data:
        datetime = exif_data['DateTime']
    else:
        datetime = strftime("%Y:%m:%d %H:%M:00", gmtime(os.path.getmtime(filename)))
    return datetime
```
