### ISSUE TITLE
AttributeError: module 'jinja2.ext' has no attribute 'with_'

### ISSUE THREAD

**Issue by toasti2000** [Psycojoker/prosopopee#147]
Hello,

I did a fresh installation on a PopOS, following the documentation and get this error when I execute "prosopopee":

`Traceback (most recent call last):
  File "/home/basti/ve/bin/prosopopee", line 8, in <module>
    sys.exit(main())
  File "/home/basti/ve/lib/python3.10/site-packages/prosopopee/prosopopee.py", line 842, in main
    templates.add_extension("jinja2.ext.with_")
  File "/home/basti/ve/lib/python3.10/site-packages/jinja2/environment.py", line 373, in add_extension
    self.extensions.update(load_extensions(self, [extension]))
  File "/home/basti/ve/lib/python3.10/site-packages/jinja2/environment.py", line 117, in load_extensions
    extension = t.cast(t.Type["Extension"], import_string(extension))
  File "/home/basti/ve/lib/python3.10/site-packages/jinja2/utils.py", line 149, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
AttributeError: module 'jinja2.ext' has no attribute 'with_'
`

What can I do?

Many thanks in advance!

**Comment by QSchulz** [comment]
Downgrade to a version of Jinja before 3.1, or patch prosopopee the same way it was done here: https://github.com/recitale/recitale/commit/5f7fb06eaaa21cde178627c8d418066efbf9514e

**Comment by toasti2000** [comment]
Perfect, many thanks! This worked perfectly!

Any advantages of [recitale](https://github.com/recitale/recitale) that Prosopopee not have?

**Comment by QSchulz** [comment]
Mainly highly parallelized build (c.f. https://github.com/Psycojoker/prosopopee/pull/137) and a bit more user-friendly in terms of progress bars during build. Otherwise, not much. I just grew tired of the build times on my slow PCs/servers and this fork using Pillow is much faster (and it was fun (sometimes) to learn more about Python).
