### ISSUE TITLE
Errors when starting prosopopee

### ISSUE THREAD

**Issue by toasti2000** [Psycojoker/prosopopee#98]
Hello,
I just installed all packages and prosopopee as written in the documentation, but got this error messages when executing "prosopopee" or "prosopopee test":
```
(ve) toasti@toasti-LXM:~/Pictures/Prosopopee/pics$ prosopopee 
warning: If you want the rss and/or the social network share to work, you need to specify the website url in root settings
Traceback (most recent call last):
  File "/home/toasti/Pictures/Prosopopee/ve/bin/prosopopee", line 8, in <module>
    sys.exit(main())
  File "/home/toasti/Pictures/Prosopopee/ve/local/lib/python2.7/site-packages/prosopopee/prosopopee.py", line 634, in main
    build_index(settings, front_page_galleries_cover, templates)
  File "/home/toasti/Pictures/Prosopopee/ve/local/lib/python2.7/site-packages/prosopopee/prosopopee.py", line 549, in build_index
    Video=Video
  File "/home/toasti/Pictures/Prosopopee/ve/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/toasti/Pictures/Prosopopee/ve/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/toasti/Pictures/Prosopopee/ve/local/lib/python2.7/site-packages/prosopopee/themes/exposure/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/toasti/Pictures/Prosopopee/ve/local/lib/python2.7/site-packages/prosopopee/themes/exposure/templates/base.html", line 33, in top-level template code
    {% block content %}
  File "/home/toasti/Pictures/Prosopopee/ve/local/lib/python2.7/site-packages/prosopopee/themes/exposure/templates/index.html", line 39, in block "content"
    {% if settings.show_date and gallery.date %}<div class="gallery-datetime">{{ gallery.date.strftime("%d %B %Y") }}</div>{% endif %}
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
```
Could you please help?

The "Themes" folder was empty, I downloaded the package and copied the themes manually into the folder.

Many thanks!

**Comment by Psycojoker** [comment]
Are you using python3 by any chance? That looks like your error (yeah, we never ported)

**Comment by toasti2000** [comment]
How can I ensure that I use V2? I did the installation exactly as written
in the documentation.

When I activated ve and install prosopopee I get this information:

(ve) basti@Basti-LXM:~$ pip install prosopopee

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: prosopopee in ./ve/lib/python2.7/site-packages (0.8.2)
Requirement already satisfied: docopt in ./ve/lib/python2.7/site-packages (from prosopopee) (0.6.2)
Requirement already satisfied: jinja2 in ./ve/lib/python2.7/site-packages (from prosopopee) (2.10.3)
Requirement already satisfied: path.py in ./ve/lib/python2.7/site-packages (from prosopopee) (11.5.2)
Requirement already satisfied: future in ./ve/lib/python2.7/site-packages (from prosopopee) (0.18.2)
Requirement already satisfied: ruamel.yaml in ./ve/lib/python2.7/site-packages (from prosopopee) (0.16.5)
Requirement already satisfied: MarkupSafe>=0.23 in ./ve/lib/python2.7/site-packages (from jinja2->prosopopee) (1.1.1)
Requirement already satisfied: importlib-metadata>=0.5 in ./ve/lib/python2.7/site-packages (from path.py->prosopopee) (0.23)
Requirement already satisfied: backports.os; python_version == "2.7" and sys_platform == "linux2" in ./ve/lib/python2.7/site-packages (from path.py->prosopopee) (0.1.1)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in ./ve/lib/python2.7/site-packages (from ruamel.yaml->prosopopee) (0.2.0)
Requirement already satisfied: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in ./ve/lib/python2.7/site-packages (from ruamel.yaml->prosopopee) (0.4.14)
Requirement already satisfied: zipp>=0.5 in ./ve/lib/python2.7/site-packages (from importlib-metadata>=0.5->path.py->prosopopee) (0.6.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in ./ve/lib/python2.7/site-packages (from importlib-metadata>=0.5->path.py->prosopopee) (4.0.2)
Requirement already satisfied: contextlib2; python_version < "3" in ./ve/lib/python2.7/site-packages (from importlib-metadata>=0.5->path.py->prosopopee) (0.6.0.post1)
Requirement already satisfied: pathlib2; python_version == "3.4.*" or python_version < "3" in ./ve/lib/python2.7/site-packages (from importlib-metadata>=0.5->path.py->prosopopee) (2.3.5)
Requirement already satisfied: more-itertools in ./ve/lib/python2.7/site-packages (from zipp>=0.5->importlib-metadata>=0.5->path.py->prosopopee) (5.0.0)
Requirement already satisfied: six in ./ve/lib/python2.7/site-packages (from pathlib2; python_version == "3.4.*" or python_version < "3"->importlib-metadata>=0.5->path.py->prosopopee) (1.12.0)
Requirement already satisfied: scandir; python_version < "3.5" in ./ve/lib/python2.7/site-packages (from pathlib2; python_version == "3.4.*" or python_version < "3"->importlib-metadata>=0.5->path.py->prosopopee) (1.10.0)

So all seems to be installed what needed.

I also tried the docker container, there I got the message "Abort: I can't find a settings.yaml in the current working directory".

**Comment by Psycojoker** [comment]
Ah no, you are in python2, my bad :/

The error is actually that you date isn't written in a format that is parsed as a correct date, so you get a string instead and that produce this crash. Make sure to see if you have written the date in the correct format '-'

You can show me your yaml files instead if you prefer.

I admit that the error isn't really good :/

**Comment by toasti2000** [comment]
Ahhhh, you are right, it was the date!
I have written it down in this way:

12-04-2018

Just changed to 2018-04-12 and all is fine.

I also defined an date_end, but only the "start date" will be shown.

This is my settings.yaml

`title: "Title"
sub_title: "Subtitle"
date: 2018-04-12
date_end: 2018-04-16
cover: IMG_20180412_135802.jpg
sections:
  - type: full-picture
    image: IMG_20180416_154535.jpg
    text:
      title: "Title"
      sub_title: "Subtitle"
      date: 2018-04-12
  - type: bordered-picture
    image: IMG_20180416_154043.jpg
  - type: text
    text: « Ship ahoi!  »

What is wrong?
`
Thank you very much for your help!

I have another question... is it possible to provide a download link for the original files on the static website?
For example I publish some photo stories for my family and want that they are able to download the original files.

**Comment by Psycojoker** [comment]
"date_end" doesn't exist in this template https://github.com/Psycojoker/prosopopee/blob/master/prosopopee/themes/exposure/templates/index.html#L39 I don't know where you've found it?

**Comment by toasti2000** [comment]
I have found that in the documentation:
https://prosopopee.readthedocs.io/en/latest/sections.html

When I add a video, I got this:

```
././Vacation: No such file or directory
Abort: ffmpeg command failed
```
Any idea? As I understand I must not configure anything for video until I want to use default settings, right? I have installed ffmpeg as mentioned in the documentation.

**Comment by toasti2000** [comment]
The video problem was no problem... it was just a blank in the folder name :-/ Works like a charm now.

But the "date_end" would absolutely a very nice thing. It's in the official documentation, so is there another template available?

**Comment by Psycojoker** [comment]
Ah, "date_end" is only available for a few sections yes, not the one you've tried to use it for.

Would you be interested in sending a patch? I don't have that much time anymore for that project :/

**Comment by toasti2000** [comment]
I already added the needed code to my local copy for a test - seems to work.
I will create a branch and do the changes next week.

Sorry, but I have another question ;-) In Germany we have umlauts like Ä,
Ö, etc.... when my folders have umlauts I get this error:

UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in
position 19: ordinal not in range(128)

It seems that it is not using UTF8 to handle the folders, the titles are OK.

Any idea?


Am Do., 7. Nov. 2019 um 09:11 Uhr schrieb Bram <notifications@github.com>:

**Comment by JocelynDelalande** [comment]
Hello !

@toasti2000 dare to post your patch in a Pull request ? 

> 
> 
> Sorry, but I have another question ;-) In Germany we have umlauts like Ä,
> Ö, etc.... when my folders have umlauts I get this error:
> 
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in
> position 19: ordinal not in range(128)
> 
> It seems that it is not using UTF8 to handle the folders, the titles are OK.

Is it happening also with Python 3 ?

Maybe open another issue because this IS another issue :-) ?

**Comment by toasti2000** [comment]
Hello,
I think it is not working with Python3, so I only tested it with 2.7
I try to post the patch respectively extension I did by the latest of the
end of the week.


Am Mi., 26. Feb. 2020 um 17:12 Uhr schrieb JocelynDelalande <
notifications@github.com>:

**Comment by JocelynDelalande** [comment]
FYI, prosopopee is running perfectly fine for me with Python 3.7.

**Comment by toasti2000** [comment]
Could you please tell me your installation steps?
Many thanks!

**Comment by JocelynDelalande** [comment]
> Could you please tell me your installation steps?

```
python3 -m venv venv
source venv/bin/activate
pip install prosopopee
```

**Comment by toasti2000** [comment]
Thank you very much - I will try this on another machine.

Prosopopee is a really nice way to create digital memories (but I also try
to create a bit analog on paper ;-)). Is there any chance to include
controls for the videos? Play / Pause buttons? On mobile phones we have
controls, not on a desktop computer. This would be very helpful!

Am Sa., 7. März 2020 um 17:43 Uhr schrieb JocelynDelalande <
notifications@github.com>:

**Comment by beudbeud** [comment]
@toasti2000 hi in version 0.9.1 i add the possibility to have controls on video

**Comment by toasti2000** [comment]
Hello,
Thank you! In the meantime I just edited my local version and added
controls, disabled loops and Auto Play.

**Comment by beudbeud** [comment]
@toasti2000 you can do PR if you want share with everyone your version
